language: python
python:
  - "3.6"
cache:
  - pip: true
  - directories:
    - $HOME/.local/share/io.parity.ethereum/
    - $TRAVIS_BUILD_DIR/paritybin
services:
  - postgresql
  - rabbitmq
before_install:
  - tests/setup/setup_psql.sh
  - tests/setup/setup_rabbitmq.sh
  - tests/setup/setup_parity.sh
install:
  - travis_retry pip install -e . -r requirements.txt
script:
- python -m pytest -vv tests/infura
- python -m pytest -vv tests/parity
